"""WeChat selector configuration with YAML persistence."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field, fields
from pathlib import Path
from typing import Any

import yaml


@dataclass
class MessageListConfig:
    """IDs for the WeChat message list screen."""

    container: str = "com.tencent.mm:id/j8g"
    chat_item: str = "com.tencent.mm:id/cj1"
    chat_name: str = "com.tencent.mm:id/kbq"
    last_time: str = "com.tencent.mm:id/otg"
    last_preview: str = "com.tencent.mm:id/ht5"
    badge: str = "com.tencent.mm:id/a_h"
    muted: str = "com.tencent.mm:id/h_5"


@dataclass
class FoldedChatsConfig:
    """IDs for the folded chats screen. container/chat_item detected at runtime."""

    container: str = "com.tencent.mm:id/odk"
    chat_item: str = "com.tencent.mm:id/cj0"
    title: str = "com.tencent.mm:id/obn"


@dataclass
class ChatViewConfig:
    """IDs for the chat conversation screen."""

    message_container: str = "com.tencent.mm:id/bp0"
    message_wrapper: str = "com.tencent.mm:id/bn1"
    message_layout: str = "com.tencent.mm:id/bkj"
    message_text: str = "com.tencent.mm:id/bkl"
    avatar_container: str = "com.tencent.mm:id/bk4"
    avatar_image: str = "com.tencent.mm:id/bk1"
    timestamp: str = "com.tencent.mm:id/br1"
    sender_name: str = "com.tencent.mm:id/brc"
    image_message: str = "com.tencent.mm:id/bkg"
    file_name: str = "com.tencent.mm:id/bju"
    input_box: str = "com.tencent.mm:id/bkk"


@dataclass
class NavigationConfig:
    """IDs for navigation elements."""

    back_button: str = "com.tencent.mm:id/actionbar_up_indicator"
    wechat_tab: str = "com.tencent.mm:id/icon_tv"  # Bottom tab text, find by text="微信"


@dataclass
class SelectorConfig:
    """Root configuration for all WeChat selectors."""

    message_list: MessageListConfig = field(default_factory=MessageListConfig)
    folded_chats: FoldedChatsConfig = field(default_factory=FoldedChatsConfig)
    chat_view: ChatViewConfig = field(default_factory=ChatViewConfig)
    navigation: NavigationConfig = field(default_factory=NavigationConfig)
    device_info: str = ""
    calibrated_at: str = ""

    def save(self, path: str | Path) -> Path:
        """Save config to YAML file."""

        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)

        header_lines = [
            "# WeChat Selector Configuration",
            "# Auto-generated by: wechat-summary calibrate",
            f"# Device: {self.device_info or 'Unknown'}",
            f"# Calibrated at: {self.calibrated_at or 'Unknown'}",
            "# Edit freely — changes take effect on next run.",
            "",
        ]
        yaml_text = yaml.safe_dump(
            asdict(self),
            allow_unicode=True,
            sort_keys=False,
            default_flow_style=False,
        )
        target.write_text("\n".join(header_lines) + yaml_text, encoding="utf-8")
        return target

    @classmethod
    def load(cls, path: str | Path) -> SelectorConfig:
        """Load config from YAML file."""

        source = Path(path)
        data = yaml.safe_load(source.read_text(encoding="utf-8")) or {}
        if not isinstance(data, dict):
            raise ValueError(f"Invalid selector config format: {source}")

        return cls(
            message_list=_build_dataclass(MessageListConfig, data.get("message_list")),
            folded_chats=_build_dataclass(FoldedChatsConfig, data.get("folded_chats")),
            chat_view=_build_dataclass(ChatViewConfig, data.get("chat_view")),
            navigation=_build_dataclass(NavigationConfig, data.get("navigation")),
            device_info=str(data.get("device_info", "")),
            calibrated_at=str(data.get("calibrated_at", "")),
        )

    @classmethod
    def default(cls) -> SelectorConfig:
        """Return config with hardcoded defaults."""

        return cls()


def load_config(config_path: str | None = None) -> SelectorConfig:
    """Load config with priority: explicit path > ./wechat_selectors.yaml > defaults."""

    if config_path:
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Config not found: {path}")
        return SelectorConfig.load(path)

    default_path = Path("./wechat_selectors.yaml")
    if default_path.exists():
        return SelectorConfig.load(default_path)

    return SelectorConfig.default()


def _build_dataclass(cls_: type, values: Any) -> Any:
    if not isinstance(values, dict):
        return cls_()
    field_names = {item.name for item in fields(cls_)}
    filtered = {key: value for key, value in values.items() if key in field_names}
    return cls_(**filtered)


__all__ = [
    "ChatViewConfig",
    "FoldedChatsConfig",
    "MessageListConfig",
    "NavigationConfig",
    "SelectorConfig",
    "load_config",
]
