"""Tests for selector configuration model and YAML persistence."""

from __future__ import annotations

from pathlib import Path

from wechat_summary.config import SelectorConfig, load_config


def test_default_config_has_expected_ids():
    config = SelectorConfig.default()

    assert config.message_list.container == "com.tencent.mm:id/j8g"
    assert config.message_list.chat_item == "com.tencent.mm:id/cj1"
    assert config.message_list.chat_name == "com.tencent.mm:id/kbq"
    assert config.message_list.last_time == "com.tencent.mm:id/otg"
    assert config.message_list.last_preview == "com.tencent.mm:id/ht5"

    assert config.chat_view.message_container == "com.tencent.mm:id/bp0"
    assert config.chat_view.message_wrapper == "com.tencent.mm:id/bn1"
    assert config.chat_view.message_text == "com.tencent.mm:id/bkl"
    assert config.chat_view.input_box == "com.tencent.mm:id/bkk"

    assert config.navigation.back_button == "com.tencent.mm:id/actionbar_up_indicator"


def test_save_creates_yaml_file(tmp_path: Path):
    config = SelectorConfig.default()
    target = tmp_path / "selectors.yaml"

    saved = config.save(target)

    assert saved == target
    assert target.exists()


def test_load_reads_yaml_file(tmp_path: Path):
    config = SelectorConfig.default()
    config.message_list.chat_name = "com.tencent.mm:id/custom_name"
    config.device_info = "Xiaomi 14 | Android 15"
    path = config.save(tmp_path / "custom.yaml")

    loaded = SelectorConfig.load(path)

    assert loaded.message_list.chat_name == "com.tencent.mm:id/custom_name"
    assert loaded.device_info == "Xiaomi 14 | Android 15"


def test_save_load_roundtrip(tmp_path: Path):
    config = SelectorConfig.default()
    config.chat_view.message_text = "com.tencent.mm:id/new_bkl"
    config.calibrated_at = "2026-03-18T14:30:00"
    path = tmp_path / "roundtrip.yaml"

    config.save(path)
    loaded = SelectorConfig.load(path)

    assert loaded == config


def test_load_config_explicit_path(tmp_path: Path):
    config = SelectorConfig.default()
    config.chat_view.input_box = "com.tencent.mm:id/new_input"
    config_path = tmp_path / "my_selectors.yaml"
    config.save(config_path)

    loaded = load_config(str(config_path))

    assert loaded.chat_view.input_box == "com.tencent.mm:id/new_input"


def test_load_config_default_path(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    config = SelectorConfig.default()
    config.message_list.last_preview = "com.tencent.mm:id/preview_x"
    config.save(tmp_path / "wechat_selectors.yaml")

    loaded = load_config()

    assert loaded.message_list.last_preview == "com.tencent.mm:id/preview_x"


def test_load_config_falls_back_to_defaults(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    loaded = load_config()

    assert loaded == SelectorConfig.default()


def test_yaml_contains_comments(tmp_path: Path):
    config = SelectorConfig.default()
    config.device_info = "Xiaomi 14 | Android 15"
    config.calibrated_at = "2026-03-18T14:30:00"
    target = tmp_path / "selectors.yaml"
    config.save(target)

    text = target.read_text(encoding="utf-8")

    assert text.startswith("# WeChat Selector Configuration")
    assert "# Auto-generated by: wechat-summary calibrate" in text
    assert "# Device: Xiaomi 14 | Android 15" in text
    assert "# Calibrated at: 2026-03-18T14:30:00" in text
